### ISSUE TITLE
I/O logic of the library

### ISSUE THREAD

**Issue by agirbau** [shiba24/event-vision-library#245]
Hello!

I want to start a discussion on the I/O logic of this library. Do we want to a) accept only pre-recorded data files or b) also accept streaming devices (cameras recording live)?

I think it is important to start the discussion because this may change the way the events (and other possible data) is handled.

**Comment by shiba24** [comment]
Hi, thank you for the question.
I think for now we want to focus on (a) the offline usecases. That means we don't support real-time recording.

The recording functionality would be great in future, but currently there exists softwares from manufacturers.

**Comment by agirbau** [comment]
Seems good to me, closing the issue
